import { Container, Flex, Title } from "@mantine/core";
import Head from "next/head";
import { EmployeeCard } from "~/components/employee-card";
import { api } from "~/utils/api";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container pb="lg">
        <Flex direction="column" gap="lg">
          <Title py="lg" order={1}>
            Employee page
          </Title>

          <EmployeeList />
        </Flex>
      </Container>
    </>
  );
}

function EmployeeList() {
  const { isLoading, data, isError } = api.employees.getAll.useQuery();

  if (isLoading) return <div>Loading...</div>;

  if (isError) return <div>Something went wrong</div>;

  if (!isLoading && !data && !isError) return <div>No data</div>;

  return (
    <Flex direction="column" gap="md">
      {data?.map((employee) => (
        <EmployeeCard key={employee.id} employee={employee} />
      ))}
    </Flex>
  );
}
